site_name: Let's Plan
repo_url: https://github.com/urbanSpatial/LetsPlanOrg
site_url: https://urbanspatial.github.io/LetsPlanOrg
edit_uri: edit/main/docs

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: "deep purple"
    accent: "pink"

plugins:
  - search
  - awesome-pages

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: '!!python/name:pymdownx.superfences.fence_div_format'
  - pymdownx.smartsymbols
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - smarty
  - fontawesome_markdown
