[hololens]
package = "holo/lens-composer-install"

[hololens.input]
files = [
    "composer.json",
    "composer.lock",

    "app/**/*.php",
    "database/factories/**",
    "database/seeds/**",
]

[hololens.composer]
args = [
    "--classmap-authoritative"
]
