[hololens]
package = "holo/lens-yarn-run"

[hololens.input]
files = [
    "package.json",
    "yarn.lock",
    "webpack.mix.js",

    "resources/js/**",
    "resources/scss/**",
]

[hololens.yarn-run]
command = "production"
output_dir = "public"

[hololens.output]
root = "public"
merge = "overlay"
