[hololens]
package = "holo/lens-yarn-run"

[hololens.input]
files = [
    "package.json",
    "yarn.lock",
    "webpack.mix.js",

    # artisan command is irrelevant to building frontend assets,
    # but laravel-mix sniffs for its presence to "see" Laravel:
    # https://github.com/JeffreyWay/laravel-mix/blob/467f0c9b01b7da71c519619ba8b310422321e0d6/src/Mix.js#L189
    "artisan",

    "resources/js/**",
    "resources/scss/**",
]

[hololens.yarn-run]
command = "production"
output_dir = "public"

[hololens.output]
root = "public"
merge = "overlay"
