[holomapping]
files = [
    "app/**",
    "bootstrap/*.php",
    "bootstrap/**/.gitignore",
    "config/**",
    "database/**",

    "public/**",
    "!public/css/**",
    "!public/fonts/**",
    "!public/js/**",
    "!public/mix-manifest.json",

    "resources/**",
    "routes/**",
    "storage/**/.gitignore",

    ".dockerignore",
    "artisan",
    "composer.json",
    "composer.lock",
    "docker-entrypoint.sh",
    "Dockerfile",
    "nginx.conf",
    "package.json",
    "server.php",
    "webpack.mix.js",
    "yarn.lock",
]
