apiVersion: v1
kind: Service
metadata:
  name: {{ include "letsplan.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "letsplan.labels" . | nindent 4 }}
    component: app
spec:
  selector:
    {{- include "letsplan.selectorLabels" . | nindent 4 }}
    component: app
  type: {{ .Values.services.app.type }}
  ports:
    - name: http
      port: {{ .Values.services.app.port }}
