{{- if .Values.configs.database }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "letsplan.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "letsplan.labels" . | nindent 4 }}
    component: database
data:
  {{- toYaml .Values.configs.database | nindent 2 }}

{{- end }}
