apiVersion: v1
kind: Service
metadata:
  name: {{ include "letsplan.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "letsplan.labels" . | nindent 4 }}
    component: database
spec:
  selector:
    {{- include "letsplan.selectorLabels" . | nindent 4 }}
    component: database
  type: {{ .Values.services.database.type }}
  ports:
    - name: postgresql
      port: {{ .Values.services.database.port }}
