apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "letsplan.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "letsplan.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.strategyType }}
  selector:
    matchLabels:
      {{- include "letsplan.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "letsplan.selectorLabels" . | nindent 8 }}

    spec:

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
          - containerPort: 80
            name: http
            protocol: TCP

          envFrom:
            {{- range $key, $value := .Values.app.secrets }}
            - secretRef:
                name: {{ $value }}
                optional: true
            {{- end }}

          env:
            - name: APP_URL
              value: https://{{ .Values.app.primary_hostname }}
            - name: REQUIRE_HTTPS
              value: 'true'
            - name: APP_DEBUG
              value: {{ if eq .Values.app.environment "development"}}'true'{{ else }}'false'{{ end }}
            - name: APP_ENV
              value: {{ .Values.app.environment }} }}
            - name: APP_NAME
              value: {{ .Release.Name }}
