apiVersion: v1
kind: Service
metadata:
  name: {{ include "letsplan.fullname" . }}-metabase
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "letsplan.labels" . | nindent 4 }}
    component: metabase
spec:
  selector:
    {{- include "letsplan.selectorLabels" . | nindent 4 }}
    component: metabase
  type: {{ .Values.services.metabase.type }}
  ports:
    - name: http
      port: {{ .Values.services.metabase.port }}
