{{- if .Values.configs.metabase }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "letsplan.fullname" . }}-metabase
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "letsplan.labels" . | nindent 4 }}
    component: metabase
data:
  {{- if not .Values.configs.metabase.MB_DB_HOST }}
  MB_DB_HOST: {{ include "letsplan.fullname" . }}-database.{{ .Release.Namespace }}.svc.cluster.local
  {{- end}}

  {{- if not .Values.configs.metabase.MB_DB_PORT }}
  MB_DB_PORT: "{{ .Values.services.database.port }}"
  {{- end}}

  {{- toYaml .Values.configs.metabase | nindent 2 }}

{{- end }}
