apiVersion: v1
kind: Service
metadata:
  name: {{ include "letsplan.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "letsplan.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.http.type }}
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    {{- include "letsplan.selectorLabels" . | nindent 4 }}
